### ISSUE TITLE
RAC code

### ISSUE THREAD

**Issue by nwisnoski** [sokole/ltermetacommunities#10]
@maxcastorani: This could be useful for some of the data summary stats. Includes some basic code for rank abundance curves and species accumulation curves: https://github.com/QuantitativeBiodiversity/Assignments/blob/master/Alpha/alpha_handout.pdf

**Comment by maxcastorani** [comment]
Thanks for sending this, Nate. I am passing along to Sydne, who is leading the RAC and SAC part of the script. She can check if this is useful on top of what she is already implementing. 

I will leave it to Sydne to close this Issue when the time comes.
