### ISSUE TITLE
Error with tidyr "select" command

### ISSUE THREAD

**Issue by maxcastorani** [sokole/ltermetacommunities#11]
**Lines 50-57 in sbc_data_code2.R:** 

```
sbc.comm.long <- sbc.comm.raw %>% 
  tbl_df() %>%
  mutate(VARIABLE_NAME = TAXON_CODE,
         OBSERVATION_TYPE = "TAXON_COUNT",
         VALUE = BIOMASS_DENS,
         VARIABLE_UNITS = "g dry per m2") %>%
  select(-TAXON_GENUS, -TAXON_SPECIES, -BIOMASS_DENS, -TAXON_CODE) 
```

**Error:**

> Error in (function (classes, fdef, mtable)  : 
>   unable to find an inherited method for function ‘select’ for signature ‘"tbl_df"’

**Comment by maxcastorani** [comment]
This fixes it I think:

`dplyr::select`

**Comment by Elizabethcase** [comment]
hi, this didn't fix (this old) issue for me.. just a heads up for others looking

**Comment by maxcastorani** [comment]
Hi Elizabeth and others,

Have you tried searching and replacing with "dplyr::select"? That usually works for me.

Max

Max Castorani | Assistant Professor | Dept. of Environmental Sciences | University of Virginia | castorani@virginia.edu<mailto:castorani@virginia.edu> | Tel: 434-243-4949 | Office: 352 Clark Hall | https://castorani.evsc.virginia.edu


On Mon, Nov 19, 2018 at 2:30 PM Elizabeth Case <notifications@github.com<mailto:notifications@github.com>> wrote:

hi, this didn't fix (this old) issue for me.. just a heads up for others looking

**Comment by rossdonaldson2** [comment]
https://github.com/tidyverse/dplyr/issues/3893

**Comment by PatrickBuerger** [comment]
replacing select with dplyr::select fixed it for me.. thanks

**Comment by kc-mcp** [comment]
had a similar issue and using dplyr::select worked for me as well.

**Comment by TimothyKuiper** [comment]
dplyr::select Worked for me thanks!

**Comment by MaC-Perez** [comment]
> This fixes it I think:
> 
> `dplyr::select`

it works for me thank you!

**Comment by kang37** [comment]
> This fixes it I think:
> 
> `dplyr::select`

It works for me. But I wonder why is that. Is it because there is another `select()` function in another package?

**Comment by indrajitg-r** [comment]
Yes, "raster" package also contains the function select().
