### ISSUE TITLE
New SBC LTER data on Google Drive

### ISSUE THREAD

**Issue by maxcastorani** [sokole/ltermetacommunities#12]
Hi all. I just updated the SBC LTER on Google Drive. I removed the first column of redundant row names and a few rows of erroneous missing data.

If you are accessing it remotely using the Google Drive ID, you are fine. If you have a local copy, please download the updated file.

Thanks,
Max

**Comment by sokole** [comment]
Is there any reason to leave this issue open?

**Comment by maxcastorani** [comment]
Nope, closing now. Thanks!
