### ISSUE TITLE
Develop script to calculate univariate metacommunity summary statistics for each time point in a time series.

### ISSUE THREAD

**Issue by sokole** [sokole/ltermetacommunities#2]
Our first task for the meta-analysis is to develop a workflow/R code to calculate the metrics in Table 1 in the [proposal](https://docs.google.com/document/d/1n_ec298Box2wxXWCx_L_Nfk9EKM0O84YMl2GU_6pa8g/edit?usp=sharing).  

I wrote a wrapper function to use Sydne's vegetraian package to calculate multiplicative diversity metrics for a metacommunity time series using long form data. 

I also have a function that appears to work for variation partitioning. I'll post that soon. 

We need code for EMS analysis, and potentially other metrics that folks think are important.

**Comment by sokole** [comment]
Nathan started working on EMS, has a looping function. We will implement a more efficient version (probably making use of the dplyr package). 

I'm still working on variation partitioning (Eric)

What other metrics do we want to calculate for a metacommunity time series? Chris Swan suggested using a beta-diversity metric that incorporates double zeros with reference to some knowledge of the total regional pool.

**Comment by NemaDude** [comment]
Would it be important to include a turnover function, or is that included in the beta-diversity metric?  Assume you're already capturing extinction, range contraction/expansion, colonization, recolonization, etc.,?

**Comment by sokole** [comment]
**Short answer**: Yes it would be important. no we haven't implemented it yet.

**Long answer**: 
It depends how you define turnover. The current version that's implemented using Jost's (2006, 2007 papers) beta-diversity metric does provide a measure of turnover using Hill numbers. The way we calculate it, it's an estimate of spatial turnover among sites at each snapshot in time.

If you're talking about a measure of turnover at a site (or within a metacommunity) with each timestep, we don't have that. However, there are a lot of options out there. For example, we could use dissimilarity to measure turnover at each site with each timestep (my colleague Bryan Brown has some papers on this, and there are many other approaches as well). I believe Lauren Hallett's codyn package has a function for this as well (Lauren, you can correct me if I'm wrong).

If you have a metric that you like, that you think would be an important measure of some aspect of metacommunity stability, please suggest it here -- **or better yet, create a new issue (green button, top right on the github issues tab) requesting we design a function** to calculate it for a metacommunity time series.
